#' getDprofilerText
#' 
#' Dprofiler help text
#'
getDprofilerText<-function(){
  
  list(
           column(6,
                  h2("What is Dprofiler ?"),
                  br(),
                  p(style="text-align: justify;",
                    strong("Dprofiler"), " is a novel platform to analysis and ", strong("score") ,"phenotypic information of samples using integration of bulk RNA-Seq and scRNA-Seq."),
                  br(),
                    p(style="text-align: justify;",
                      "Biospecimen collected from multiple sources of experimental and technical conditions often exhibit", 
                    strong("diverse molecular profiles and patterns."), "Each individual sample presents an additional source of information towards elucidating 
           biological mechanisms, and each sample may even be more informative than the differential expression between phenotypic conditions."),
                  p(style="text-align: justify;",
                  "Understanding complex patterns of expression profiles are essential to solving diseases, and such knowledge can only be generated by 
                  using advanced statistical measures and methods that are capable of computationally modeling and", strong("separately investigating molecular profiles of each sample.")),
                  p(style="text-align: justify;",
                    "To deciphering these complex molecular profiles within gene expression datasets, we have developed", strong("Dprofiler.")),
                  p(style="text-align: justify;",
                  "This application computationally profiles a set of targeted samples by connecting them to reference expression datasets with phenotypic profiles of interest.
                   Building on these reference profiles of phenotypic groups, Dprofiler evaluates bulk RNA samples, detect possibly existing anomalies and heterogeneities, 
                   and further explores causes and sources of distinct molecular patterns with the aid of single cell maps and other reference gene expression datasets."),
                  p(style="text-align: justify;",
                  "Users are allowed to use a variety of algorithms to calculate a ", strong("Membership Score"), "of samples associated to some phenotypic profiles of interest. 
                   Dprofiler derives reference phenotypic profiles from submitted datasets, cell-types of single cell maps and conditions from external gene expression data sets. 
                   Membership scores are universally interpretable, and indicate the similarity of a sample to these reference profiles.
                   "),
                  br(),
                  p("Dprofiler offers multiple capabilities using these three components: "),
                    tags$ul(
                      tags$li(strong("Computational Profiling: "), "Scoring and Profiling submitted samples using homogeneouos subpopulations of phenotypic reference profiles within the same dataset."),
                      tags$li(strong("Cellular Composition Analysis: "), "Infering the cellular composition of each scored sample with a reference scRNA data and estimate fractions of cellular compositions."),
                      tags$li(strong("Comparative Profiling: "), "Scoring and Profiling samples using targeted phenotypic profiles of a reference bulk expression data set.")
                    ),
                  p("Dprofiler is based on a recently developed Shiny (R) application, DEBrowser, an interactive tool for DE analysis and visualization. DEBrowser incorporates 
                  DESeq2, EdgeR, and Limma coupled with shiny to produce real-time changes within your plot queries and allows for interactive browsing of your DE results. 
                  DEBrowser also manipulates your results in a way that allows for interactive plotting by which changing padj or fold change limits also changes the displayed graph(s)."),
                  p("For more information, please visit Dprofiler documentation from ",a("this link", href = "https://dprofiler-docs.readthedocs.io/en/latest/"),".")
                  ),
           column(4,
                  br(),
                  br(),
                  br(),
                  tags$img(src = "www/images/DprofilerWorkflow.png", width="100%", height= "100%")
                  )
  )
  
}

#' getIntroText
#' 
#' Dprofiler help text
#'
getIntroText<-function(){
  
  list(
    column(8,
      
      ####
      ## Data input section ####
      ####
      
      h3("1. Data input"),
      p("There are three types input data in Dprofiler. These are: "),
      tags$ul(
        tags$li(strong("Bulk Expression Data: "), "used for profiling samples within and establish homogeneous reference profiles."),
        tags$li(strong("scRNA Expression Data Object: "), "used for deconvoluting Bulk RNA data and infering cellular compositions of these bulk samples."),
        tags$li(strong("Reference Bulk Expression Data: "), "used for comparative profiling of the Bulk data set using reference phenotypic profiles of reference bulk data set(s)."),
      ),
      p(style="text-align: justify;",
      "For both submitted Bulk and Reference Bulk expression data, there are two distinct inputs given in '.txt', '.csv' or '.tsv' formats.
        These are Count Data File and Metadata File where uploading metadata is optional."),
      p("However, for scRNA data set, the user should provide an ", 
        a("ExpressionSet",href = "https://www.bioconductor.org/packages/devel/bioc/vignettes/Biobase/inst/doc/ExpressionSetIntroduction.pdf"), 
      " object."),
      p("In addition, users may connect to DolphinMeta using their credentials to import reference bulk expression data from any Dmeta project."),
      p("If you do not have a dataset to upload, you can use the built in demo data file by 
    clicking on the 'Load Demo Vitiligo' button that loads a case study. To view the entire demo data file, you can 
    download."),
      tags$ol(
        tags$li(a("PRJNA554241",href="https://www.ncbi.nlm.nih.gov/bioproject/PRJNA554241"),": a bulk RNA-Seq count data of lesional and non-lesional vitiligo skin samples 
        processed by the RNA-Seq pipeline of ", a("DolphinNext", href = "https://github.com/UMMS-Biocore/dolphinnext"),"."),
        tags$li(a("scVitiligo",href="https://www.science.org/doi/10.1126/scitranslmed.abd8995"),": a reference scRNA-Seq count data of lesional and non-lesional vitiligo skin samples."),
        tags$li(a("GSE65127",href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE65127"),": an external bulk microarray data of vitiligo skin samples where the gene set is union of 
                differentially expressed genes across four conditions: healthy, lesional, non-lesional and peri-lesional.")
      ),
      h4("1.1 Count Data File"),            
      p(style="text-align: justify;",
      "This input file could be provided for both submitted and reference bulk datasets and it should contain summarized count 
      results of all samples in the experiment, an example of the expected input data format is presented as below:"),
      p("Note: the count file of the external reference count data should typically include only the genes that are differentially expressed."),
      tableOutput("countFile"),
      p(style="text-align: justify;",
      "Where columns are samples, rows are the mapped genomic features 
    (e.g. genes, isoforms, miRNAs, ATAC or Chip regions etc.)."),
      h4("1.2 Metadata File"),
      p(style="text-align: justify;",
      "In addition to the count data file; you may also upload metadata file to correct for 
  batch effects or any other normalizing conditions you might want to address that might be
  within your results. To handle for these conditions, simply create a metadata file by 
  using the example table at below:"),
      tableOutput("metaFile"),
      h4("1.3 scRNA Data File"),
      p(style="text-align: justify;",
        "However, for scRNA data set, the user should provide an",
        a("ExpressionSet",href = "https://www.bioconductor.org/packages/devel/bioc/vignettes/Biobase/inst/doc/ExpressionSetIntroduction.pdf"),
        "whose metadata (pData(`You Expression Set Object`)) should contain the following variables or columns:", strong(" (i) "), "sample associated to each barcode",  
        strong(" (ii) "), "total UMI counts of each barcode",  strong(" (iii) "), "cell annotation or label",
        strong(" (iv) "), "other categorical and numerical variables relavant to barcodes"),
      p("To be able to upload all data please press ", strong("Upload"), ". "),
      p(style="text-align: justify;",
      "After sucessfully uploading your data, you should see the summary of your data in the 'Upload Summary' sections. 
        To move the filtering section please click ",  strong("Filter"), ". "),
      p("If you are ready to use Dprofiler, please click 'Upload' menu on the left to start using Dprofiler.")

    )
  )
}

#' getDataAssesmentText
#' 
#' Dprofiler help text
#'
getDataAssesmentText<-function(){
  list(
    column(8,
      h3("2. Data Processing"),
      p(style="text-align: justify;", "Dprofiler implements data processing routines of DEBrowser."),
      h4("2.1 Filtering"),    
      p(style="text-align: justify;",
        "In this section, you can simultaneously visualize the changes of your submitted dataset 
      while filtering out the low count genes. Choose your filtration criteria from ", 
      strong("Filtering Methods"), " box which is located just center of the screen. 
      Three methods are available to be used:"),
      tags$ul(
        tags$li(strong("Max:"), "Filters out genes where maximum count for each gene across all samples are less 
     than defined threshold."),
        tags$li(strong("Mean:"), "Filters out genes where mean count for each gene are less than defined threshold."),
        tags$li(style="text-align: justify;",
        strong("CPM:"), "First, counts per million (CPM) is calculated as the raw counts divided by the 
      library sizes and multiplied by one million. Then it filters out genes where at least 
      defined number of samples is less than defined CPM threshold.")
      ),
      withMathJax(),
      p(style="text-align: justify;",
        "The expression cutoff value is determined according to the library size 
      and normalization factors with formula $$\\text{CPM} = \\frac{\\text{raw counts}}{\\text{library size} * \\text{normalization factors}} * 10^{-6}$$ 
      For example, if the cutoff CPM value is 10,
      the library size and normalization factors are estimated approximately equal to \\(\\ 3 \\text{ x} 10 ^ 6\\) and 1 for at least 4 samples, 
      then 10 CPM expression cutoff corresponds to about 30 read counts. 
      Therefore, in this example features in more than 4 samples have less than 
      30 read counts (10 CPM) is going to be low expression features
      and will be removed for batch effect correction and DE analysis."),
      p("To be able to filter out the low expression counts please press", strong("Filter"), "."),
      
      h4("2.2. Batch Effect Correction and Normalization"),
      p("After filtering low count features, you may continue your analysis with Batch Effect 
      Detection & Correction or directly jump to Computational Profiling."),
      p(style="text-align: justify;",
       "With metadata file containing your batch correction fields 
      then you have the option to conduct ",strong("batch effect correction"), " prior to 
      your analysis. By adjusting parameters of ", strong("Options") ," box, you can investigate 
      your dataset further. These parameters of the ", strong("Options"), " box are 
      explained as followed:"),
      tags$ol(
        tags$li(style="text-align: justify;",
        strong("Normalization Method:"), "Dprofiler allows performing normalization 
      prior the batch effect correction. You may choose your normalization method 
      (among MRE, TMM, RLE, upperquartile), or if you don't want to normalize your 
      data you can select none for this item."),
        tags$li(style="text-align: justify;",
          strong("Correction Method:"), "Dprofiler uses ",
          a("ComBat", href = "https://bioconductor.org/packages/release/bioc/html/sva.html"),
          " (part of the SVA bioconductor package) or ",
          a("Harman", href = "https://www.bioconductor.org/packages/release/bioc/vignettes/Harman/inst/doc/IntroductionToHarman.html"),
          "to adjust for possible batch effect or conditional biases."),
        tags$li(style="text-align: justify;",
         strong("Treatment:"), "Please select the column that is specified in 
      metadata file for comparision, such as cancer vs control. It is named 
      condition for our sample metadata."),
        tags$li(style="text-align: justify;",
        strong("Batch:"), "Please select the column name in metadata file 
      which differentiate the batches. For example in our metadata, it is called batch.
      Upon clicking submit button, comparison tables and plots will be created on the right 
      part of the screen as shown below."),
      ),
      p("You can investigate the changes on the data by comparing following features:"),
      tags$ul(
        tags$li("Read counts for each sample"),
        tags$li("PCA, IQR and Density plot of the dataset"),
        tags$li("Gene/region vs samples data")
      ),
      p(style="text-align: justify;",
        "After batch effect correction, user can click ", strong("Go to Computational Profiling"),
        " button to start profiling samples of the submitted gene expression dataset.")
    )
  )
}

#' getCompProfilingText
#' 
#' Dprofiler help text
#'
getCompProfilingText <-function(){
  list(
    column(6,
      h3("3. An Iterative Algorithm for Computational Profiling of Bulk Samples"),
      p(style="text-align: justify;",
        "Dprofiler provides methods for calculating membership scores to be used to profiling samples associated to phenotypic profiles of interest with the submitted dataset."),
      p(style="text-align: justify;", 
        "By iteratively removing samples with low scores and repeatatively testing for differentially expressed genes, computational profiling analysis of 
         Dprofiler converges if there are no more low-scored samples left in the data set. The final list of samples with high membership scores establish 
         homogeneous (pure) reference profiles of these phenotypic groups, and they are used to calculate the final score to establish the profile of 
         each individual sample:"),
      tags$ul(
        tags$li("Conducts a DE analysis (DESeq2, EdgeR or Limma) given remaining samples within the data."),
        tags$li(style="text-align: justify;",
                "Estimates the membership scores (based on either Silhouette and NNLS) of all samples given expression profiles limited to differentially expressed genes"),
        tags$li("Removes samples with low membership scores."),
        tags$li("Repeats until no more samples have to be removed from the data.")
      ),
      p("Parameters that are used to conduct Computational Profiling are:"),
      tags$ul(
        tags$li(strong("Score Method:"), " The algorithm to determine membership scores of each individual sample:",
                tags$ul(
                  tags$li(style="text-align: justify;",
                          strong("Silhouette "), "estimates the score via the normalized difference between 
                          average distances to the samples of one condition and average distance to the ones of the other condition."),
                  tags$li(style="text-align: justify;",
                          strong("NNLS "), "estimates the score with a non-negative least squares regression model where each 
                          sample modeled against mean expression profiles of samples from each condition.")
                )
        ),
        tags$li(style="text-align: justify;",
                strong("Min. Score:"), " A threshold for membership scores to determine dismembered samples of the dataset,
                samples whose scores are smaller than the threshold are eliminated on each iteration. Reference profiles are calculated given 
                non-removed samples, and membership scores of all samples are calculated given reference profiles on final step."
        ),
        tags$li(strong("DE Selection Method:"), " The protocol for selecting DE genes on each iteration:",
                tags$ul(
                  tags$li(strong("log2FC+Padj:"), "selects DE genes whose log fold changes are higher and adjusted p-values are lower 
                          than a predetermined value."),
                  tags$li(strong("Top n Stat:"), "selects DE genes whose test statistics are among the top highest statistics associated to all genes."),
                )
        )
      ),
      p(style="text-align: justify;", 
        "Users who wish to analyze the data further should click ", strong("Go to Cellular Compositions"), " button to initiate an RNA deconvolution using 
        the reference scRNA data set, or ", strong("Go to Comparative Profiling"), "to calculate Membership Scores given an external bulk gene expression data set.")
    ),
    column(3,
           br(),
           br(),
           tags$img(src = "www/images/InteractiveSilhouette.png", width="100%", height= "100%")
    ),
    column(9,
      
      h4("3.2 DE analysis"),
      p("The goal of differential gene expression analysis is to find genes
  or transcripts whose difference in expression, when accounting for the
  variance within condition, is higher than expected by chance."),
      tags$ul(
        tags$li(
          a("DESeq2", href="https://bioconductor.org/packages/release/bioc/html/DESeq2.html"),
          "is an R package available via Bioconductor and is designed to normalize count 
          data from high-throughput sequencing assays such as RNA-Seq and test for
          differential expression (Love et al. 2014).  With multiple parameters such as
          padjust values, log fold changes, plot styles, and so on, altering plots
          created with your DE data can be a hassle as well as time consuming. The
          Differential Expression Browser uses DESeq2 (Love et al., 2014)."
        ),
        tags$li(
          a("EdgeR",href="https://bioconductor.org/packages/release/bioc/html/edgeR.html"),
          "(Robinson et al., 2010), and ",
          a("Limma", href="https://bioconductor.org/packages/release/bioc/html/limma.html"),
          "(Ritchie et al., 2015) coupled with shiny (Chang, W. et al., 2016)
          to produce real-time changes within your
          plot queries and allows for interactive browsing of your DE results.
          In addition to DE analysis, Dprofiler also offers a variety of other plots
          and analysis tools to help visualize your data even further."),
      ),
      p("Parameters that are used to conduct DE analysis are:"),
      tags$ul(
        tags$li(strong("DESeq2"),
                tags$ol(
                  tags$li(strong("fitType:"), " either 'parametric', 'local', or 'mean' for the type of fitting of 
                          dispersions to the mean intensity. See estimateDispersions for description."),
                  tags$li(strong("betaPrior:"), " whether or not to put a zero-mean normal prior on the non-intercept 
                          coefficients See nbinomWaldTest for description of the calculation of 
                          the beta prior. By default, the beta prior is used only for the Wald test, 
                          but can also be specified for the likelihood ratio test."),
                  tags$li(strong("testType:"), " either 'Wald' or 'LRT', which will then use either Wald significance tests 
                          (defined by nbinomWaldTest), or the likelihood ratio test on the difference in 
                          deviance between a full and reduced model formula (defined by nbinomLRT).")
                )
          
        )
      ),
      tags$ul(
        tags$li(strong("EdgeR"),
                tags$ol(
                  tags$li(strong("Normalization:"), " calculate normalization factors to scale the raw library sizes. Values 
                          can be 'TMM','RLE','upperquartile','none'."),
                  tags$li(strong("Dispersion:"), " either a numeric vector of dispersions or a character string indicating 
                          that dispersions should be taken from the data object."),
                  tags$li(strong("testType:"), "ExactTest or glmLRT.",
                          tags$ul(
                            tags$li(strong("exactTest:")," computes p-values for differential 
                                    abundance for each gene between two samples, conditioning on the total 
                                    count for each gene. The counts in each group are assumed to follow a 
                                    binomial distribution. "),
                            tags$li(strong("glmLRT:")," fits a negative binomial generalized 
                                    log-linear model to the read counts for each gene and conducts 
                                    genewise statistical tests.")
                          )
                  ),
                )
                
        )
      ),
      tags$ul(
        tags$li(strong("Limma"),
                tags$ol(
                  tags$li(strong("Normalization:"), " calculate normalization factors to scale the raw library sizes. Values 
                          can be 'TMM','RLE','upperquartile','none'."),
                  tags$li(strong("Fit Type:"), " fitting method; 'ls' for least squares or 'robust' for robust regression."),
                  tags$li(strong("Norm. Bet. Arrays:"), " normalization Between Arrays; Normalizes expression intensities so that the 
                          intensities or log-ratios have similar distributions across a set of arrays.")
                )
                
        )
      )
    )
  )
}

#' getCompCellularText
#' 
#' Dprofiler help text
#'
getCompCellularText <-function(){
  list(
    column(6,
           h3("4. Cellular Composition Analysis using Reference scRNA Datasets"),
           
           p(style="text-align: justify;",
             "Dprofiler provides methods for Deconvolution of Bulk RNA expression data sets using annotated reference single cell RNA datasets where
              the percentage of each cell type or state (i.e. cellular composition) in each bulk RNA sample is estimated. Dprofiler primarily uses", 
             a("MuSIC", href="https://xuranw.github.io/MuSiC/articles/MuSiC.html"),
             "algorithm for Deconvolution."),
           p("Parameters that are used to conduct Cellular Composition Analysis are:"),
           tags$ul(
             tags$li(strong("Select Meta:"), " identification type that specifies the reference profiles such as cell states, cell types, or sub cell type."),
             tags$li(strong("Identifications:"), " a list of reference profiles specified in Select Meta (e.g. Keratinocytes, Melanoytes etc.)"),
             tags$li(strong("Samples:"), " the column in metadata that specifies samples of the barcodes (e.g. Patients, Donors etc.)"),
             tags$li(strong("DE genes: "), " the strategy for selecting genes to deconvolute bulk samples",
                     tags$ul(
                       tags$li(strong("Heterogeneous Conditions:"), " DE genes of Heterogeneous (original) conditions of submitted bulk RNA dataset."),
                       tags$li(strong("Homogeneous Conditions:"), " DE genes of Homogeneous conditions found by Computational Profiling of submitted bulk RNA dataset."),
                       tags$li(strong("Marker Genes:"), " identification-based (selected metadata) marker genes of single cell data expression profiles."),
                     )
             )
           ),
           p(style="text-align: justify;",
             "The MuSIC algorithm employs single cell genomic expression profiles to acquire non-negative least squares estimates of bulk gene 
             expression datasets (Wang et al.). A specific feature of MUSIC allows the proportions of closely related cell types to be correctly estimated. 
             To deal with collinearity, MuSiC employs a tree-guided procedure that recursively zooms in on closely related cell types. Rather than pre-selecting marker genes 
             from scRNA-seq based only on mean expression, MuSIC gives weight to each gene allowing for the use of a larger set of genes in deconvolution. 
             The weighting scheme prioritizes consistent genes across subjects:"), 
           tags$ul(
             tags$li(strong("(i) "), "up-weighing genes with low cross-subject variance (informative genes) and"),
             tags$li(strong("(ii) "), "down-weighing genes with high cross-subject variance (non-informative genes).")),
           p("This requirement on cross-subject consistency is critical for transferring cell type-specific gene expression information from one dataset to another.")
    ),
    column(4,
           br(),
           br(),
           tags$img(src = "www/images/rnadeconvolution.png", width="100%", height= "100%")
    )
  )
}

#' getComparativeProfText
#' 
#' Dprofiler help text
#'
getComparativeProfText <-function(){
  list(
    column(6,
           h3("5. Comparative Profiling using Reference Datasets of Bulk Samples"),
           p(style="text-align: justify;",
             "Dprofiler provides methods for calculating membership scores given phenotypic profiles of external reference bulk samples to profile
             the samples of the submitted bulk samples."),
           p("The gene expression profiles of the external reference bulk samples are often limited to genes of interest where Dprofiler
             uses an overlapping set of differentially expressed genes of submitted data set and gene profiles of reference bulk data sets to 
             compute membership scores."),
           p("Parameters that are used to conduct iterative DE analysis are:"),
           tags$ul(
             tags$li(strong("Select Series:"), " name of the dataset (or Series), if the external data imported from Dmeta, multiple datasets might be available
                     to the users."),
             tags$li(strong("Select Meta:"), " metadata variable for conditions/phenotypes."),
             tags$li(strong("Score Method:"), " the algorithm to determine membership scores of each individual sample:",
                     tags$ul(
                       tags$li(style="text-align: justify;",
                               strong("Silhouette "), "estimates the score via the normalized difference between 
                          average distances to the samples of one condition and average distance to the ones of the other condition."),
                       tags$li(style="text-align: justify;",
                               strong("NNLS "), "estimates the score with a non-negative least squares regression model where each 
                          sample modeled against mean expression profiles of samples from each condition.")
                     )
             )
           )
    ),
    column(3,
           br(),
           br(),
           br(),
           tags$img(src = "www/images/ComparativeSilhouette.png", width="100%", height= "100%")
    )
  )
}

#' getQAText
#' 
#' Dprofiler help text
#'
getQAText<-function(){
  list(
    h3("5. Frequently asked questions (FAQ)"),
    h4("5.1 Why un-normalized counts?"),
    p("DESeq2 requires count data as input obtained from 
          RNA-Seq or another high-thorughput sequencing experiment 
          in the form of matrix values. Here we convert un-integer 
          values to integer to be able to run DESeq2. The matrix values 
          should be un-normalized, since DESeq2 model internally corrects for 
          library size. So, transformed or normalized values such as counts 
          scaled by library size should not be used as input. Please use edgeR 
          or limma for normalized counts."),
    h4("5.2 Why am I getting error while uploading files?"),
    p("* Dprofiler supports tab, comma or semi-colon separated files. However spaces or characters in numeric regions not supported and causes an error while uploading files. It is crutial to remove these kind of instances from the files before uploading files."),
    p("* Another reason of getting an error is using same gene name multiple times. This may occurs after opening files in programs such as Excel, which tends to automatically convert some gene names to dates (eg. SEP9 to SEP.09.2018). This leads numerous problems therefore you need to disable these kind of automatic conversion before opening files in these kind of programs."),
    p("* Some files contain both tab and space as an delimiter which lead to error. It is required to be cleaned from these kind of files before loading."),
    h4("5.3 Why some columns not showed up after upload?"),
    p("If a character in numeric area or space is exist in one of your column, either column will be eliminated or you will get an error. Therefore it is crutial to remove for these kind of instances from your files before uploading."),
    h4("5.4 Why am I getting error while uploading CSV/TSV files exported from Excel?"),
    p("* You might getting an error, because of using same gene name multiple times. This may occurs after opening files in programs such as Excel, which tends to automatically convert some gene names to dates (eg. SEP9 to SEP.09.2018). Therefore you need to disable these kind of automatic conversion before opening files in these kind of programs."),
    h4("5.5 Why can't I see all the background data in Main Plots?"),
    p("In order to increase the performance, by default 10% of non-significant(NS) genes are used to generate plots. We strongly suggest you to use all of the NS genes in your plots while publishing your results. You can easily change this parameter by clicking **Main Options** button and change Background Data(%) to 100% on the left sidebar."),
    h4("5.6 Why am I getting error when I click on DE Genes in Go Term Analysis?"),
    p("To start ", strong("Go Term"), " analysis, it is important to select correct organism from ", strong("Choose an organism"), " field. After selecting other desired parameters, you can click ", strong("Submit")," button to run Go Term analysis. After this stage, you will able to see", strong(" categories")," regarding to your selected gene list in the ", strong("Table")," Tab. Once you select this category, you can click DE Genes button to see gene list regarding to selected category."),
    h4("5.7 How to download selected data from Main plots/QC Plots/Heatmaps?"),
    p("First, you need to choose ", strong("Choose dataset"), " field as ",strong("selected")," under ",strong("Data Options")," in the left sidebar. When you select this option, new field: ",strong("The plot used in selection")," will appear under ", strong("Choose dataset")," field. You need to specify the plot you are interested from following options: Main plot, Main Heatmap, QC Heatmap. Finally you can click ", strong("Download Data"), " button to download data, or if you wish to see the selected data, you can click ",strong("Tables")," tab.")
  )
}

